name: flutters_tips_and_tricks
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.0
  cupertino_icons: ^1.0.5
  file: ^6.1.2
  flutter_bloc: 8.1.1
  platform: ^3.1.0
  shared_preferences: ^2.0.15
  equatable: ^2.0.5
  json_annotation: ^4.7.0
  freezed_annotation: ^2.1.0
  http: ^0.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  bloc_test: ^9.1.0
  lint: ^1.10.0
  mockito: ^5.3.2
  build_runner: ^2.2.1
  freezed: ^2.1.1
  json_serializable: ^6.4.1
  dart_code_metrics: ^4.21.0

dependency_overrides:
  analyzer: ^5.1.0

flutter:
  uses-material-design: true
