name: flutters_tips_and_tricks
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  file: ^6.1.2
  platform: ^3.1.0
  flutter_riverpod: ^2.0.2
  shared_preferences: ^2.0.15
  equatable: ^2.0.5
  json_annotation: ^4.7.0
  freezed_annotation: ^2.1.0
  http: ^0.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  #  dart_code_metrics: ^4.14.0
  # We use 'lint' package rather than default 'flutter_lints' package because it is more
  # restrictive which is considered a good thing as it allows for stronger and more coherent
  # coding practice in a team. This package implements around 75% of linter rules
  # versus only 45% for flutter_lints
  # See this article for more info: https://rydmike.com/blog_flutter_linting.html
  lint: ^1.10.0
  mockito: ^5.3.2
  build_runner: ^2.2.1
  freezed: ^2.1.1
  json_serializable: ^6.4.1

flutter:
  uses-material-design: true
