name: flutters_tips_and_tricks
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc: ^8.1.0
  cupertino_icons: ^1.0.5
  dio: ^4.0.6
  equatable: ^2.0.5
  file: ^6.1.2
  flutter_bloc: 8.1.1
  freezed_annotation: ^2.1.0
  get_it: 7.2.0
  http: ^0.13.5
  i69n: 2.1.0
  injectable: 1.5.3
  json_annotation: ^4.7.0
  logger: ^1.1.0
  platform: ^3.1.0
  retrofit: ^3.3.1
  shared_preferences: ^2.0.15
  auto_route: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  bloc_test: ^9.1.0
  build_runner: ^2.2.1
  dart_code_metrics: ^4.21.0
  freezed: ^2.1.1
  injectable_generator: ^1.5.4
  json_serializable: ^6.4.1
  lint: ^1.10.0
  mockito: ^5.3.2
  retrofit_generator: ^4.0.0
  auto_route_generator: ^5.0.3

dependency_overrides:
  analyzer: ^4.7.0

flutter:
  uses-material-design: true
