name: flutters_tips_and_tricks
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  file: ^6.1.2
  platform: ^3.1.0
  flutter_riverpod: ^2.0.0-dev.0
  shared_preferences: ^2.0.12
  equatable: ^2.0.3
  freezed_annotation: ^1.1.0
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  dart_code_metrics: ^4.14.0
  # We use 'lint' package rather than default 'flutter_lints' package because it is more
  # restrictive which is considered a good thing as it allows for stronger and more coherent
  # coding practice in a team. This package implements around 75% of linter rules
  # versus only 45% for flutter_lints
  # See this article for more info: https://rydmike.com/blog_flutter_linting.html
  lint: ^1.8.2
  mockito: ^5.0.17
  mocktail: ^0.3.0
  build_runner: ^2.1.7
  freezed: ^1.1.0
  json_serializable: ^6.1.3

flutter:
  uses-material-design: true
